spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_project
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: robi
    password: robi
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: vU5eTqT8cA5R9xg1XzMvGz1fB8u7m8eOr5RZqJoB4mc
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  port: 8088