services:
  postgres:
    container_name: postgres-sql-authproj
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DATA: /var/lib/postgresql/data
      POSTGRES_DB: auth_project
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-authproj
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025


networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
