services:
  db:
    container_name: postgres-spring-boot-course
    image: postgres:latest
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:  # ✅ This should be outside 'services'
  db:
    driver: bridge

volumes:  # ✅ This should also be outside 'services'
  db:
